import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Banner from '../components/banner/banner';
import NavBar from '../components/nav/navbar';
import SectionCards from '../components/card/section-cards';

// Import video fetching functions
import { getPopularVideos, getVideos } from "../lib/videos";

// Define getServerSideProps to pre-render the page
export async function getServerSideProps() {
  // Fetch videos for each section
  const dreamworksVideos = await getVideos("dreamworks trailer");
  const kurzgesagtVideos = await getVideos("kurzgesagt");
  const infographicsVideos = await getVideos("infographics channel");
  const popularVideos = await getPopularVideos();

  // Return the video data as props
  return {
    props: {
      dreamworksVideos,
      kurzgesagtVideos,
      infographicsVideos,
      popularVideos,
    },
  };
}

// Define the Home component
export default function Home({
  dreamworksVideos,
  kurzgesagtVideos,
  infographicsVideos,
  popularVideos,
}) {
  // Return the Home component
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <NavBar username="W@William.com" />
        <Banner
          videoId="dBxxi5XAm3U"
          title="Clifford the red dog"
          subTitle="A children's story"
          imgUrl="/static/clifford.webp"
        />

        <div className={styles.sectionWrapper}>
          <SectionCards
            title="dreamworks"
            videos={dreamworksVideos}
            size="large"
          />
          <SectionCards
            title="kurzgesagt"
            videos={kurzgesagtVideos}
            size="small"
          />
          <SectionCards
            title="The Infographics Show"
            videos={infographicsVideos}
            size="medium"
          />
          <SectionCards title="popular" videos={popularVideos} size="small" />
        </div>
      </div>
    </div>
  );
}