import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Banner from '../components/banner/banner';
import NavBar from '../components/nav/navbar';


export default function Home() {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username="W@William.com"/>
      <Banner
        title='Clifford the red dog'
        subTitle='A childrens story'
        imgUrl='/static/clifford.webp' />

      {/* {<NavBar />
      
      <Card />} */}

    </div>
  );
}
