import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Banner from '../components/banner/banner';
import NavBar from '../components/nav/navbar';
import SectionCards from '../components/card/section-cards';

// Import video fetching functions
import { getPopularVideos, getVideos, getWatchItAgainVideos } from "../lib/videos";

// Define getServerSideProps to pre-render the page
export async function getServerSideProps() {
  const userId = 'did:ethr:0xdE8963Ce3c067bd3ef53D60Fd58e0cA44cB2ed68';
  const token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJkaWQ6ZXRocjoweGRFODk2M0NlM2MwNjdiZDNlZjUzRDYwRmQ1OGUwY0E0NGNCMmVkNjgiLCJwdWJsaWNBZGRyZXNzIjoiMHhkRTg5NjNDZTNjMDY3YmQzZWY1M0Q2MEZkNThlMGNBNDRjQjJlZDY4IiwiZW1haWwiOiJ3aWxsaGN1cnJ5QGdtYWlsLmNvbSIsIm9hdXRoUHJvdmlkZXIiOm51bGwsInBob25lTnVtYmVyIjpudWxsLCJ1c2VybmFtZSI6bnVsbCwid2FsbGV0cyI6W10sImlhdCI6MTcyNjQzODAwMywiZXhwIjoxNzI3MDQyODAzLCJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWFsbG93ZWQtcm9sZXMiOlsidXNlciIsImFkbWluIl0sIngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS11c2VyLWlkIjoiZGlkOmV0aHI6MHhkRTg5NjNDZTNjMDY3YmQzZWY1M0Q2MEZkNThlMGNBNDRjQjJlZDY4In19.QGoc80yJJQ01c39wqw9g4kMReRRQfMa50XU0zVOkvy4';
  const watchItAgainVideos = await getWatchItAgainVideos(userId, token);

  console.log({watchItAgainVideos});
  

  const dreamworksVideos = await getVideos("dreamworks trailer");
  const kurzgesagtVideos = await getVideos("kurzgesagt");
  const infographicsVideos = await getVideos("infographics channel");
  const popularVideos = await getPopularVideos();

  // Return the video data as props
  return {
    props: {
      dreamworksVideos,
      kurzgesagtVideos,
      infographicsVideos,
      popularVideos,
      watchItAgainVideos
    },
  };
}

// Define the Home component
export default function Home({
  dreamworksVideos,
  kurzgesagtVideos,
  infographicsVideos,
  popularVideos,
  watchItAgainVideos
}) {
  // Return the Home component
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <NavBar username="W@William.com" />
        <Banner
          videoId="dBxxi5XAm3U"
          title="Kurzgesagt"
          subTitle="Time Travel"
          imgUrl="/static/clifford.webp"
        />

        <div className={styles.sectionWrapper}>
          <SectionCards
            title="dreamworks"
            videos={dreamworksVideos}
            size="large"
          />
          <SectionCards
            title="Watch it again"
            videos={watchItAgainVideos}
            size="small"
          />
          <SectionCards
            title="kurzgesagt"
            videos={kurzgesagtVideos}
            size="small"
          />
          <SectionCards
            title="The Infographics Show"
            videos={infographicsVideos}
            size="medium"
          />
          <SectionCards title="popular" videos={popularVideos} size="small" />
        </div>
      </div>
    </div>
  );
}