import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Banner from '../components/banner/banner';
import NavBar from '../components/nav/navbar';
import SectionCards from '../components/card/section-cards';

import { getPopularVideos, getVideos } from "../lib/videos";



export async function getServerSideProps() {
  const dreamworksVideos = await getVideos("dreamworks trailer");
  const kurzgesagtVideos = await getVideos("kurzgesagt");
  const infographicsVideos = await getVideos("infographics channel");
  const popularVideos = await getPopularVideos();

  return { props: { dreamworksVideos, kurzgesagtVideos, infographicsVideos, popularVideos } }
}


export default function Home({ 
  dreamworksVideos, 
  kurzgesagtVideos, 
  infographicsVideos, 
  popularVideos 
}) {
  
  

  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
            <NavBar username="W@William.com"/>
            <Banner
              title='Clifford the red dog'
              subTitle='A childrens story'
              imgUrl='/static/clifford.webp'
            />

        <div className={styles.sectionWrapper}>
          <SectionCards title='dreamworks' videos={dreamworksVideos} size="large" />
          <SectionCards title='kurzgesagt' videos={kurzgesagtVideos} size="small" />
          <SectionCards title='The Infographics Show' videos={infographicsVideos} size="medium" />
          <SectionCards title='popular' videos={popularVideos} size="small" />
        </div>
      </div>
    </div>
  );
}
